### ISSUE TITLE
Add a few things to Game Section

### ISSUE THREAD

**Issue by akxks** [mikeroyal/Apple-Silicon-Guide#5]
I love this guide, however you can make it better by adding games support lists (https://applesilicongames.com/ and https://www.applegamingwiki.com/wiki/Home)

I think you might have briefly linked CrossOver (at the top of the list!) however, you can also put it below Gaming Section (where steam and Xbox streaming is) and highlight the fact that you can play AAA games inside of MacOS with the help of CrossOver and Wine compatibility translation built into this app, also other resources such as PortingKit which work in a similar fashion but with some different games supported see (https://www.portingkit.com/) and its games (https://www.portingkit.com/games)

Another is Rosetta2 (OS automatically translating games -- check App Store in MacOS for Shadow of Tomb Raider)

You could also mention Parallels inside of Gaming section as Parallels has a Gaming feature to optimize it a little bit for DirectX games (yes its virtualised like you mentioned in a different section so you lose a bit of FPS) but its still really good on a lot of games (see YT Vids)

https://www.youtube.com/watch?v=oet8GoDopVc 
https://www.youtube.com/watch?v=nAXP_PTNY2k 
https://www.youtube.com/watch?v=si_vhQU9lPA

**Comment by mikeroyal** [comment]
Thanks, I added it to the guide. :smile:
