### ISSUE TITLE
Docker - Lima

### ISSUE THREAD

**Issue by cpressland** [mikeroyal/Apple-Silicon-Guide#6]
Hello, are pull requests welcome? I’d like to add a section about [Lima](https://github.com/lima-vm/lima)

fantastic resource here BTW.

**Comment by HugeIRL** [comment]
From the bottom of the README:


`If would you like to contribute to this guide simply make a [Pull Request](https://github.com/mikeroyal/Apple-Silicon-Guide/pulls).`

**Comment by mikeroyal** [comment]
Thanks, I added it to the guide. :smile:
