### ISSUE TITLE
DOS Box Boxer

### ISSUE THREAD

**Issue by JMonster973** [mikeroyal/Apple-Silicon-Guide#73]
Boxer is a DOSBOX frontend that allowed you to easily import your game through drag and drop. You can then customize and make app wrappers.
https://boxer.thec0de.com/
This is a fork of the original to make it 64-bit

**Comment by mikeroyal** [comment]
Thanks, I'll take a look at it.

**Comment by mikeroyal** [comment]
Okay, a PR has made to add Boxer. Thank you for the suggestion.

**Comment by JMonster973** [comment]
Thanks!
